name: Unit Tests
on: [push]
jobs:
  run:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ 'ubuntu-latest', 'windows-latest' ]
        php-versions: [ '8.1' ]
    steps:
      - name: Checkout Source.
        uses: actions/checkout@v2
      - name: Setup PHP 8.1
        if: ${{ matrix.php-versions == '8.1' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          extensions: mbstring, intl
      - name: Run PHPUnit
        run: |
          composer install
          php vendor/bin/phpunit tests --bootstrap vendor/autoload.php --coverage-clover ./coverage.xml
      - name: Push to Codecov Probably
        if: ${{ matrix.php-versions == '8.1' && matrix.operating-system == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          verbose: true
